from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_gateway_type = sa.Enum(
        "TELEGRAM_STARS",
        "YOOKASSA",
        "YOOMONEY",
        "CRYPTOMUS",
        "HELEKET",
        name="paymentgatewaytype",
    )

    currency = sa.Enum("USD", "XTR", "RUB", name="currency")

    plan_type = sa.Enum("TRAFFIC", "DEVICES", "BOTH", "UNLIMITED", name="plantype")

    plan_availability = sa.Enum(
        "ALL",
        "NEW",
        "EXISTING",
        "INVITED",
        "ALLOWED",
        name="planavailability",
    )

    promocode_reward_type = sa.Enum(
        "DURATION",
        "TRAFFIC",
        "SUBSCRIPTION",
        "PERSONAL_DISCOUNT",
        "PURCHASE_DISCOUNT",
        name="promocoderewardtype",
    )

    user_role = sa.Enum("DEV", "ADMIN", "USER", name="userrole")

    locale = sa.Enum(
        "AR",
        "AZ",
        "BE",
        "CS",
        "DE",
        "EN",
        "ES",
        "FA",
        "FR",
        "HE",
        "HI",
        "ID",
        "IT",
        "JA",
        "KK",
        "KO",
        "MS",
        "NL",
        "PL",
        "PT",
        "RO",
        "RU",
        "SR",
        "TR",
        "UK",
        "UZ",
        "VI",
        name="locale",
    )

    subscription_status = sa.Enum(
        "ACTIVE",
        "DISABLED",
        "LIMITED",
        "EXPIRED",
        name="subscriptionstatus",
    )

    transaction_status = sa.Enum(
        "PENDING",
        "COMPLETED",
        "CANCELED",
        "REFUNDED",
        name="transactionstatus",
    )

    purchase_type = sa.Enum("NEW", "RENEW", "CHANGE", name="purchasetype")

    payment_gateway_type = sa.Enum(
        "TELEGRAM_STARS",
        "YOOKASSA",
        "YOOMONEY",
        "CRYPTOMUS",
        "HELEKET",
        name="paymentgatewaytype",
    )

    op.create_table(
        "payment_gateways",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", payment_gateway_type, nullable=False),
        sa.Column("currency", currency, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", plan_type, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("traffic_limit", sa.Integer(), nullable=False),
        sa.Column("device_limit", sa.Integer(), nullable=False),
        sa.Column("availability", plan_availability, nullable=False),
        sa.Column("allowed_user_ids", sa.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("squad_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "promocodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("reward_type", promocode_reward_type, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("reward", sa.Integer(), nullable=True),
        sa.Column("lifetime", sa.Integer(), nullable=True),
        sa.Column("max_activations", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", user_role, nullable=False),
        sa.Column("language", locale, nullable=False),
        sa.Column("personal_discount", sa.Integer(), nullable=False),
        sa.Column("purchase_discount", sa.Integer(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("is_bot_blocked", sa.Boolean(), nullable=False),
        sa.Column("is_trial_used", sa.Boolean(), nullable=False),
        sa.Column("current_subscription_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_remna_id", sa.UUID(), nullable=False),
        sa.Column("status", subscription_status, nullable=False),
        sa.Column("expire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("user_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_telegram_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_user_telegram_id"),
        "subscriptions",
        ["user_telegram_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_users_current_subscription",
        "users",
        "subscriptions",
        ["current_subscription_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "plan_durations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promocode_activations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("promocode_id", sa.Integer(), nullable=False),
        sa.Column("user_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "activated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["promocode_id"],
            ["promocodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_telegram_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("status", transaction_status, nullable=False),
        sa.Column("purchase_type", purchase_type, nullable=False),
        sa.Column("gateway_type", payment_gateway_type, nullable=False),
        sa.Column("pricing", sa.JSON(), nullable=False),
        sa.Column("currency", currency, nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("user_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_telegram_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_table(
        "plan_prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("currency", currency, nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("plan_duration_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plan_duration_id"], ["plan_durations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.bulk_insert(
        sa.table(
            "payment_gateways",
            sa.column("type", payment_gateway_type),
            sa.column("currency", currency),
            sa.column("is_active", sa.Boolean),
            sa.column("settings", sa.JSON),
        ),
        [
            {
                "type": "TELEGRAM_STARS",
                "currency": "XTR",
                "is_active": True,
                "settings": None,
            },
            {
                "type": "YOOKASSA",
                "currency": "RUB",
                "is_active": False,
                "settings": {
                    "type": "YOOKASSA",
                    "shop_id": None,
                    "key": None,
                    "customer": None,
                    "vat_code": None,
                },
            },
            {
                "type": "YOOMONEY",
                "currency": "RUB",
                "is_active": False,
                "settings": {
                    "type": "YOOMONEY",
                    "wallet_id": None,
                    "key": None,
                },
            },
            {
                "type": "CRYPTOMUS",
                "currency": "USD",
                "is_active": False,
                "settings": {
                    "type": "CRYPTOMUS",
                    "merchant_id": None,
                    "key": None,
                },
            },
            {
                "type": "HELEKET",
                "currency": "USD",
                "is_active": False,
                "settings": {
                    "type": "HELEKET",
                    "merchant_id": None,
                    "key": None,
                },
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plan_prices")
    op.drop_table("transactions")
    op.drop_table("promocode_activations")
    op.drop_table("plan_durations")
    op.drop_table("users")
    op.drop_index(op.f("ix_subscriptions_user_telegram_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_table("promocodes")
    op.drop_table("plans")
    op.drop_table("payment_gateways")
    # ### end Alembic commands ###
