from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promocode_activations",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("promocode_id", sa.Integer(), nullable=False),
        sa.Column("user_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "activated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["promocode_id"], ["promocodes.id"]),
        sa.ForeignKeyConstraint(["user_telegram_id"], ["users.telegram_id"]),
    )

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", "LIMITED", "EXPIRED", name="subscriptionstatus"),
            nullable=False,
        ),
        sa.Column("expire_at", sa.DateTime(), nullable=True),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("user_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_telegram_id"], ["users.telegram_id"]),
    )

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("payment_id", sa.UUID(), nullable=False, unique=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "CANCELED", "REFUNDED", name="transactionstatus"),
            nullable=False,
        ),
        sa.Column(
            "gateway",
            sa.Enum(
                "TELEGRAM_STARS",
                "YOOKASSA",
                "YOOMONEY",
                "CRYPTOMUS",
                "HELEKET",
                name="paymentgatewaytype",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.Column("currency", sa.Enum("USD", "XTR", "RUB", name="currency"), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("user_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_telegram_id"], ["users.telegram_id"]),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("subscriptions")
    op.drop_table("promocode_activations")
    # ### end Alembic commands ###
