from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plans", sa.Column("squad_ids", sa.ARRAY(sa.UUID()), nullable=False))
    op.alter_column("plans", "traffic_limit", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("plans", "device_limit", existing_type=sa.INTEGER(), nullable=False)

    op.add_column(
        "promocodes",
        sa.Column(
            "reward_type",
            sa.Enum(
                "DURATION",
                "TRAFFIC",
                "SUBSCRIPTION",
                "PERSONAL_DISCOUNT",
                "PURCHASE_DISCOUNT",
                name="promocoderewardtype",
            ),
            nullable=False,
        ),
    )
    op.add_column("promocodes", sa.Column("reward", sa.Integer(), nullable=True))
    op.add_column("promocodes", sa.Column("max_activations", sa.Integer(), nullable=True))
    op.drop_column("promocodes", "is_multi_use")
    op.drop_column("promocodes", "duration")
    op.drop_column("promocodes", "type")
    op.drop_column("promocodes", "discount_percent")
    op.drop_column("promocodes", "traffic")
    op.drop_column("promocodes", "activated_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promocodes", sa.Column("activated_by", sa.BIGINT(), nullable=True))
    op.add_column("promocodes", sa.Column("traffic", sa.INTEGER(), nullable=True))
    op.add_column("promocodes", sa.Column("discount_percent", sa.INTEGER(), nullable=True))
    op.add_column(
        "promocodes",
        sa.Column(
            "type",
            sa.Enum(
                "DURATION",
                "TRAFFIC",
                "SUBSCRIPTION",
                "PERSONAL_DISCOUNT",
                "PURCHASE_DISCOUNT",
                name="promocoderewardtype",
            ),
            nullable=False,
        ),
    )
    op.add_column("promocodes", sa.Column("duration", sa.INTEGER(), nullable=True))
    op.add_column("promocodes", sa.Column("is_multi_use", sa.BOOLEAN(), nullable=False))
    op.drop_column("promocodes", "max_activations")
    op.drop_column("promocodes", "reward")
    op.drop_column("promocodes", "reward_type")
    op.alter_column("plans", "device_limit", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("plans", "traffic_limit", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("plans", "squad_ids")
    # ### end Alembic commands ###
