from typing import Optional, Protocol, runtime_checkable

from src.application.dto import UserDto
from src.core.enums import Role


@runtime_checkable
class UserDao(Protocol):
    async def create(self, user: UserDto) -> UserDto: ...

    async def get_by_telegram_id(self, telegram_id: int) -> Optional[UserDto]: ...

    async def get_by_telegram_ids(self, telegram_ids: list[int]) -> list[UserDto]: ...

    async def get_by_partial_name(self, query: str) -> list[UserDto]: ...

    async def get_by_referral_code(self, referral_code: str) -> Optional[UserDto]: ...

    async def get_all(self, limit: int = 100, offset: int = 0) -> list[UserDto]: ...

    async def update(self, user: UserDto) -> Optional[UserDto]: ...

    async def delete(self, telegram_id: int) -> bool: ...

    async def count(self) -> int: ...

    async def exists(self, telegram_id: int) -> bool: ...

    async def filter_by_role(self, role: list[Role]) -> list[UserDto]: ...

    async def set_bot_blocked_status(self, telegram_id: int, is_bot_blocked: bool) -> None: ...

    async def clear_current_subscription(self, telegram_id: int) -> None: ...

    async def get_blocked_users(self) -> list[UserDto]: ...

    async def get_recent_activity_users(
        self,
        excluded_ids: list[int] | None = None,
    ) -> list[UserDto]: ...

    async def get_recent_registered_users(self, limit: int = 5) -> list[UserDto]: ...

    async def unblock_all(self) -> None: ...

    async def count_blocked(self) -> int: ...

    async def has_any_subscription(self, telegram_id: int) -> bool: ...

    async def is_invited_user(self, telegram_id: int) -> bool: ...

    async def toggle_blocked_status(self, telegram_id: int) -> None: ...
